steps:
  - id: 'Get secret from GCS bucket'
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - cp
      - gs://${_BUCKET_NAME}/secret
      - .
    entrypoint: gsutil
  - id: 'Get k8s cluster credentials'
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - container
      - clusters
      - get-credentials
      - ${_K8S_CLUSTER_NAME}
      - --region
      - asia-southeast2
      - --project
      - $PROJECT_ID
    entrypoint: gcloud
  - id: 'Update k8s secret'
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: ['-c','kubectl create secret generic endpoint-secret --from-file=secret=./secret --save-config --dry-run=client -n ${_K8S_NAMESPACE} -o yaml | kubectl apply -f -']
    entrypoint: '/bin/bash'
  
