apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 103.107.198.243/32
