apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: helloweb-gateway-http
  namespace: default
spec:
  # google kubernetes engine layer 7 regional internal load balancer
  # see https://cloud.google.com/kubernetes-engine/docs/how-to/gatewayclass-capabilities
  gatewayClassName: gke-l7-rilb
  listeners:
  - name: helloweb-listener-http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
---
apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: helloweb-policy-http
  namespace: default
spec:
  default:
    # this GCPGatewayPolicy exists only to enable global access on the Gateway's LB
    allowGlobalAccess: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: helloweb-gateway-http
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: helloweb-httproute-http
  namespace: default
spec:
  parentRefs:
  - name: helloweb-gateway-http
  hostnames:
  - test.zxcvhs.com
  rules:
  - backendRefs: # ClusterIP Service
    - name: helloweb
      port: 80
