apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              name: configmap-env-demo # The ConfigMap name
              key: player_initial_lives # The key
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap-env-demo
              key: ui_properties_file_name
      resources:
        requests:
          cpu: 200m
          memory: 250mi
        limits:
          cpu: 200m
          memory: 250mi
