apiVersion: v1
kind: Service
metadata:
  name: helloweb
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "cloud-armor-cfg"}'
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30011
  type: NodePort
