apiVersion: v1
kind: Pod
metadata:
  name: configmap-file-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 200m
          memory: 250mi
        limits:
          cpu: 200m
          memory: 250mi
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        name: configmap-file-demo
        items:
          - key: "game.properties"
            path: "game.properties"
          - key: "user-interface.properties"
            path: "user-interface.properties"
